---
title: "Flow beim Laufen (interindividell)"
author: "Simon Bogutzky"
date: "30. März 2016"
output: html_document
---

```{r load-data, include=FALSE}

# Remove all variables
rm(list = ls(all = T)) 

# Load functions
source("./code-snippets/functions.r")

# Set root path
if(dir.exists("C:/Users/sbogutzky/Desktop/data/2016"))
  root.path <- "C:/Users/sbogutzky/Desktop/data/2016/"

# Define Colors
colors <- c("#3FADCB", "#33D100", "white")

# Load participant directories
participant.dirs <- list.dirs(path = paste(root.path, "features/baseline/", sep = ""), full.names = F, recursive = F)
participant.count <- length(participant.dirs)

# Set activity directory
activity.dir <- "laufen"

# Collect data
data.1 <- data.frame()
data.1b <- data.frame()

for (i in 1:participant.count) {
  
  subjects <- factor(i, levels = 1:participant.count)
  
  participant.dir <- participant.dirs[i]
  
  # Load FSS features baseline
  fss.feature.path <- paste(root.path, "features/baseline/", participant.dir, "/", "fss-features.csv", sep = "")
  fss.features <- read.csv(fss.feature.path)
  data.1b <- rbind(data.1b, data.frame(subject = subjects, fss.features[, 1:5]))
  
  # Load FSS features activity
  fss.feature.path <- paste(root.path, "features/", activity.dir, "/", participant.dir, "/", "fss-features.csv", sep = "")
  fss.features <- read.csv(fss.feature.path)
  
  # Load HRV features
  kubios.hrv.feature.path <- list.files(path = paste(root.path, "features/", activity.dir, "/", participant.dir, sep = ""), pattern = "imu-rn42-bd38-1_hrv.txt", full.names = T, recursive = T)
  kubios.hrv.features <- read.table(kubios.hrv.feature.path, header = T, sep = ",", nrows = 1)
  
  # Load JC features
  #source("code-snippets/load-jc-features.R")
  
  # Load CLS features
  cls.index.path <- list.files(path = paste(root.path, "preprocessed/", activity.dir, "/", participant.dir, sep = ""), pattern = "cls-indexes-1.csv", full.names = T, recursive = T)
  cls.indexes <- read.csv(cls.index.path, skip = 2)
  cls.indexes <- cls.indexes[complete.cases(cls.indexes), ]
  
  # Create data frame
  data.1 <- rbind(data.1, data.frame(subject = subjects, fss.features[, 1:5], kubios.hrv.features[, c(4, 6, 17, 18)], t(colMeans(cls.indexes[, 2:3]))))
  
}
rm(i, participant.dir, subjects, fss.feature.path, fss.features, kubios.hrv.feature.path, kubios.hrv.features, cls.index.path, cls.indexes)

rownames(data.1) <- seq(length = nrow(data.1))
rownames(data.1b) <- seq(length = nrow(data.1b))

```

```{r distribution, echo=FALSE, message=FALSE, warning=FALSE}

par("mfcol" = c(1, 1), mar = c(2.5, 2.5, 2.5, 3.5) + 0.1, mgp = c(1.5, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

hist(data.1$absorption, main = "Absorption", xlab = "Absorption")
print(shapiro.test(data.1$absorption))

```

```{r linear-models, echo=FALSE, message=FALSE, warning=FALSE}

par("mfcol" = c(2, 2), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

print("-----------------Mean HR-----------------")
plot(data.1$absorption ~ data.1$meanhr, xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.1$meanhr, data.1$absorption, x.lim = c(30, 200), sub.line = 1.3, interval = 1)
print("-----------------------------------------")

print("-----------------RMSSD-------------------")
plot(data.1$absorption ~ data.1$rmssd, xlab = "RMSSD", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.1$rmssd, data.1$absorption, x.lim = c(0, 20), sub.line = 1.3, interval = .5)
print("-----------------------------------------")

# print("-----------------Jerk Cost---------------")
# plot(data.1$absorption ~ data.1$mean.jerk.cost, xlab = "Jerk Cost", ylab = "Absorption", pch = 21, bg = colors[1])
# PlotModels(data.1$mean.jerk.cost, data.1$absorption, x.lim = c(1, 10), sub.line = 1.3, interval = .005)
# print("-----------------------------------------")
# 
# print("-----------------Cycle Interval----------")
# plot(data.1$absorption ~ data.1$mean.cycle.interval, xlab = "Cycle Interval", ylab = "Absorption", pch = 21, bg = colors[1])
# PlotModels(data.1$mean.cycle.interval, data.1$absorption, x.lim = c(.25, 2), sub.line = 1.3, interval = .001)
# print("-----------------------------------------")

print("-----------------PCoI--------------------")
plot(data.1$absorption ~ data.1$pcoi, xlab = "PCoI", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.1$pcoi, data.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
print("-----------------------------------------")

print("----------------NSEI---------------------")
plot(data.1$absorption ~ data.1$nsei, xlab = "NSEI", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.1$nsei, data.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
print("-----------------------------------------")

```

```{r substract-baseline-absorption, message=FALSE, warning=FALSE, include=FALSE}

data.2 <- data.1
data.2$absorption <- data.2$absorption - data.1b$absorption

```

```{r distribution-1, echo=FALSE, message=FALSE, warning=FALSE}

par("mfcol" = c(1, 1), mar = c(2.5, 2.5, 2.5, 3.5) + 0.1, mgp = c(1.5, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

hist(data.2$absorption, main = "Absorption", xlab = "Absorption")
print(shapiro.test(data.2$absorption))

```

```{r linear-models-1, echo=FALSE, message=FALSE, warning=FALSE}
par("mfcol" = c(2, 2), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

print("-----------------Mean HR-----------------")
plot(data.2$absorption ~ data.2$meanhr, xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.2$meanhr, data.2$absorption, x.lim = c(30, 200), sub.line = 1.3, interval = 1)
print("-----------------------------------------")

print("-----------------RMSSD-------------------")
plot(data.2$absorption ~ data.2$rmssd, xlab = "RMSSD", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.2$rmssd, data.2$absorption, x.lim = c(0, 20), sub.line = 1.3, interval = .5)
print("-----------------------------------------")

# print("-----------------Jerk Cost---------------")
# plot(data.2$absorption ~ data.2$mean.jerk.cost, xlab = "Jerk Cost", ylab = "Absorption", pch = 21, bg = colors[1])
# PlotModels(data.2$mean.jerk.cost, data.2$absorption, x.lim = c(1, 10), sub.line = 1.3, interval = .005)
# print("-----------------------------------------")
# 
# print("-----------------Cycle Interval----------")
# plot(data.2$absorption ~ data.2$mean.cycle.interval, xlab = "Cycle Interval", ylab = "Absorption", pch = 21, bg = colors[1])
# PlotModels(data.2$mean.cycle.interval, data.2$absorption, x.lim = c(.25, 2), sub.line = 1.3, interval = .001)
# print("-----------------------------------------")

print("-----------------PCoI--------------------")
plot(data.2$absorption ~ data.2$pcoi, xlab = "PCoI", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.2$pcoi, data.2$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
print("-----------------------------------------")

print("----------------NSEI---------------------")
plot(data.2$absorption ~ data.2$nsei, xlab = "NSEI", ylab = "Absorption", pch = 21, bg = colors[1])
PlotModels(data.2$nsei, data.2$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
print("-----------------------------------------")

```

```{r stroboscopic-technique, echo=FALSE, message=FALSE, warning=FALSE}

max.nsei <- which.max(data.2$nsei)
min.nsei <- which.min(data.2$nsei)

participant.dir <- participant.dirs[min.nsei]

cls.phase.path <- list.files(path = paste(root.path, "preprocessed/", activity.dir, "/", participant.dir, sep = ""), pattern = "cls-phases-1.csv", full.names = T, recursive = T)

cls.phases <- read.csv(cls.phase.path, skip = 2)
cls.phases <- cls.phases[complete.cases(cls.phases), ]

par("mfcol" = c(1, 1), mar = c(2.5, 2.5, .5, 1.5) + 0.1, mgp = c(1.5, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "i", yaxs = "i")

plot(cls.phases$t.s, cls.phases$psi,xlab = "", ylab = expression(Psi(t)), ylim = c(0, 1), pch = 21, bg = "#3FADCB")

```

```{r view}
View(cbind(data.2, participant.dirs))
```

