---
title: "Flow beim Gehen"
author: "Simon Bogutzky"
date: "16. November 2015"
output: html_document
---

```{r set-directories, echo = FALSE}

# Remove all variables
rm(list = ls(all = T)) 

# Set root data directory path
root.data.directory.path <- ""
if(file.exists("/Volumes/flow/Documents/archiv/daten/2015/flow-gehen-und-laufen"))
  root.data.directory.path        <- "/Volumes/flow/Documents/archiv/daten/2015/flow-gehen-und-laufen/"
if(file.exists("//gangstore.ddns.net/flow/Documents/archiv/daten/2015/flow-gehen-und-laufen"))
  root.data.directory.path        <- "//gangstore.ddns.net/flow/Documents/archiv/daten/2015/flow-gehen-und-laufen/"

# Set activity directory
activity.directory        <- "walking/" 

# Set user directory
user.directory            <- "lochwitz-andreas/"

require(flow)

CreateFeatureDataFrame <- function(directory.path, filename, cols, rows, col.names, additional.features, skip = skip) {
  feature.data.frame <- data.frame()
  if(file.exists(paste(directory.path, file.name, sep = ""))) {
    loaded.features <- read.csv(paste(directory.path, file.name, sep = ""), skip = skip)
    for (i in rows) {
      feature.vector        <- c(loaded.features[i, cols], additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  } else {
    for (i in rows) {
      feature.vector        <- c(rep(NA, length(cols)), additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  }
  return(feature.data.frame)
}

DetectAnnomalies <- function(x, y, x.lab, y.lab, x.lim, y.lim, epsilon = 0) {
  X <- matrix(data = c(x, y), nrow = length(y), ncol = 2)
  plot(X[,1], X[,2], xlab = x.lab, ylab = y.lab, pch = 21, xlim = x.lim, ylim = y.lim)
  
  gl <- EstimateGaussian(X)
  p  <- MultivariateGaussian(X, gl$mu, gl$sigma2)
  
  if(epsilon == 0) {
    y <- zeros(nrow(X), 1)
    y[identify(X)]  <- 1
    bt              <- SelectThreshold(y, p)
    epsilon         <- bt$epsilon
  }
  
  outliers <- which(p < epsilon)
  points(X[outliers, 1], X[outliers, 2], xlab = x.lab, ylab = y.lab, pch = 21, bg = 2)
  
  return(list("epsilon" = epsilon, "outliers" = outliers))  
}

```

```{r load-data, echo=FALSE}

par(mfcol = c(1, 1), mgp = c(2.5, 1, 0))

# Load FSS features
fss.features <- read.csv(paste(root.data.directory.path, "features/", activity.directory, user.directory, "fss-features.csv", sep = ""))

# Create data frame for HRV features
hrv.features <- data.frame()

# Create data frame for JC features
jc.features  <- data.frame()
epsilon      <- 0

# Create data frame for CLS features
cls.features <- data.frame()

# Load data per session
for (i in 1:nrow(fss.features)) {
  
  # Set additional features
  additional.features <- fss.features[i, c(6:13)]
  activity.start      <- additional.features[, 2]
  measurement         <- additional.features[, 5]
  
  if(measurement == 1) {
    date.directory <- paste(strftime(as.POSIXct(activity.start / 1000, origin = "1970-01-01", tz="CET"), format="%Y-%m-%d--%H-%M-%S"), "/", sep ="")
  }
  
  # Create HRV feature data frame
  directory.path  <- paste(root.data.directory.path, "features/", activity.directory, user.directory, "kubios-hrv-features/", date.directory, sep="")
  file.name       <- paste("ecg-data-", measurement, "_hrv.txt", sep = "")
  col.names       <- c("sample","meanrr","sdnn","meanhr","sdhr","rmssd","nn50","pnn50","sdann","sdnni","hrvtri","tinn","vlfpeakfft","lfpeakfft","hfpeakfft","vlfpowfft","lfpowfft","hfpowfft","vlfpowprfft","lfpowprfft","hfpowprfft","lfpownufft","hfpownufft","totpowfft","lfhffft","vlfpeakar","lfpeakar","hfpeakar","vlfpowar","lfpowar","hfpowar","vlfpowprar","lfpowprar","hfpowprar","lfpownuar","hfpownuar","totpowar","lfhfar","edr","sd1","sd2","apen","sampen","d2","dfa1","dfa2","activity","activity.start","activity.end","inquiry.end","measurement","last.name","first.name","date.of.birth")
  feature.data.frame  <- CreateFeatureDataFrame(directory.path, file.name, 1:46, 1:3, col.names, additional.features, skip = 0)
  hrv.features        <- rbind(hrv.features, feature.data.frame)
  hrv.features$rmssd[hrv.features$rmssd > 39] = NA
  
  # Load jerk cost, estimate and create JC feature data frame
  directory.path        <- paste(root.data.directory.path, "processed-data/", activity.directory, user.directory, date.directory, sep = "")
  file.name             <- paste("leg-jerk-cost-data-", measurement, ".csv", sep = "")
  col.names             <- jerk.cost.feature.names   <- c("mean.cycle.interval", "mean.jerk.cost", "activity","activity.start","activity.end","inquiry.end","measurement","last.name","first.name","date.of.birth")
  range.intervals       <- seq(0, 900, 300)
  
  feature.data.frame <- data.frame()
  if(file.exists(paste(directory.path, file.name, sep = ""))) {
    data        <- read.csv(paste(directory.path, file.name, sep = ""), skip = 2)
    
    data[, 3]   <- data[, 3] / 10^5
    annomalies  <- DetectAnnomalies(data[, 2], data[, 3], expression("Cycle Interval ("~s~")"), expression("JC (x"~10^5~m^2*s^{-5}~")"), c(.8, 1.3), c(0, 8), epsilon = epsilon) 
    data        <- data[-annomalies$outliers, ]
    epsilon     <- annomalies$epsilon
    
    for (j in 1:(length(range.intervals) - 1)) {
      estimated.features <- c(mean(data[, 2][data[, 1] >= range.intervals[j] & data[, 1] < range.intervals[j + 1] & data[, 2] < 1.15], na.rm = T), mean(data[, 3][data[, 1] >= range.intervals[j] & data[, 1] < range.intervals[j + 1] & data[, 2] < 1.15], na.rm = T))
      feature.vector        <- c(estimated.features, additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  } else {
    for (j in 1:(length(range.intervals) - 1)) {
      feature.vector        <- c(rep(NA, 2), additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  }
  jc.features        <- rbind(jc.features, feature.data.frame)
  
  # Load CLS, estimate and create CLS feature data frame
  directory.path        <- paste(root.data.directory.path, "processed-data/", activity.directory, user.directory, date.directory, sep = "")
  file.name             <- paste("leg-cls-indexes-", measurement, ".csv", sep = "")
  col.names             <- c("mean.pcoi", "mean.nsei", "activity","activity.start","activity.end","inquiry.end","measurement","last.name","first.name","date.of.birth")
  range.intervals       <- seq(0, 900, 300)
  
  feature.data.frame <- data.frame()
  if(file.exists(paste(directory.path, file.name, sep = ""))) {
    data        <- read.csv(paste(directory.path, file.name, sep = ""), skip = 2)
    plot(data[, 2], data[, 3], xlab ="PCoI", ylab = "NSEI", xlim = c(0, 1), ylim = c(0, 1))  
    for (j in 1:(length(range.intervals) - 1)) {
      
      estimated.features <- c(mean(data[, 2][data[, 1] >= range.intervals[j] & data[, 1] < range.intervals[j + 1]], na.rm = T), mean(data[, 3][data[, 1] >= range.intervals[j] & data[, 1] < range.intervals[j + 1]], na.rm = T))
      feature.vector        <- c(estimated.features, additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  } else {
    for (j in 1:(length(range.intervals) - 1)) {
      feature.vector        <- c(rep(NA, 2), additional.features)
      names(feature.vector) <- col.names
      feature.data.frame    <- rbind(feature.data.frame, feature.vector)
    }
  }
  cls.features        <- rbind(cls.features, feature.data.frame)
}

# Remove unused stuff
rm(additional.features, data, feature.data.frame, activity.start, annomalies, col.names, date.directory, directory.path, epsilon, estimated.features, feature.vector, file.name, measurement,i, j, range.intervals)
```

# Ebenenspezifisch
```{r time-series, echo=FALSE}

breaks  <- rep(1:3, nrow(fss.features)) 
starts  <- seq(1, nrow(fss.features), by = 4)
dates   <- format(as.POSIXct(fss.features$activity.end/1000, origin = "1970-01-01", tz = "CET"), "%D", tz = "CET")

absorption.expression <- expression("FSS FII: Absorption")
meanhr.expression     <- expression("Mean HR ("~BPM~")")
rmssd.expression      <- expression("RMSSD ("~s~")")
jerk.cost.expression  <- expression("Mean JC (x"~10^5~m^2*s^{-5}~")")

par(mfcol = c(4, 1), mar = c(3.5, 4, 0, 4) + 0.1, mgp = c(2.5, 1, 0))

plot(fss.features$absorption, xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = absorption.expression, xlab = "")
axis(1, at = starts, labels = F)
box()

plot(hrv.features$meanhr[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = meanhr.expression, xlab = "")
axis(1, at = starts, labels = F)
box()

plot(hrv.features$rmssd[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = rmssd.expression, xlab = "")
axis(1, at = starts, labels = F)
box()

plot(jc.features$mean.jerk.cost[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = jerk.cost.expression, xlab = "Measurement")
axis(3, at = starts, labels = dates[starts])
axis(1, at = starts)
box()

rm(breaks, starts, dates)
```

```{r time-series-2, echo=FALSE}
breaks  <- rep(1:3, nrow(fss.features)) 
starts  <- seq(1, nrow(fss.features), by = 4)
dates   <- format(as.POSIXct(fss.features$activity.end/1000, origin = "1970-01-01", tz = "CET"), "%D", tz = "CET")

pcoi.expression  <- expression("Mean PCoI")
nsei.expression  <- expression("Mean NSEI")

par(mfcol = c(4, 1), mar = c(3.5, 4, 0, 4) + 0.1, mgp = c(2.5, 1, 0))

plot(cls.features$mean.pcoi[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = "Mean CLS Indexes", xlab = "", ylim = c(0,1))
points(cls.features$mean.nsei[breaks == 3], pch = 22, bg = c("green", "white", "white", "white"), cex = 1.2)
axis(1, at = starts, labels = F)
box()

plot(hrv.features$meanhr[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = meanhr.expression, xlab = "")
axis(1, at = starts, labels = F)
box()

plot(hrv.features$rmssd[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = rmssd.expression, xlab = "")
axis(1, at = starts, labels = F)
box()

plot(jc.features$mean.jerk.cost[breaks == 3], xaxt = "n", pch = 21, bg = c("green", "white", "white", "white"), cex = 1.2, ylab = jerk.cost.expression, xlab = "Measurement")
axis(3, at = starts, labels = dates[starts])
axis(1, at = starts)
box()

rm(breaks, starts, dates)
```

# Korrelation
```{r linear-models, echo=FALSE}
breaks  <- rep(1:3, nrow(fss.features)) 
par(mfrow = c(2, 2), mar = c(3.5, 4, 1, 4) + 0.1, mgp = c(2.5, 1, 0))

linear.model <- lm(fss.features$flow ~ hrv.features$meanhr[breaks == 3])
summary(linear.model)
plot(hrv.features$meanhr[breaks == 3], fss.features$absorption, pch = 21, cex = 1.2, ylab = absorption.expression, xlab = meanhr.expression)
abline(linear.model)
box()

linear.model <- lm(fss.features$flow ~ hrv.features$rmssd[breaks == 3])
summary(linear.model)
plot(hrv.features$rmssd[breaks == 3], fss.features$absorption, pch = 21, cex = 1.2, ylab = absorption.expression, xlab = rmssd.expression)
abline(linear.model)
box()

linear.model <- lm(fss.features$flow ~ (jc.features$mean.jerk.cost[breaks == 3]))
summary(linear.model)
plot(jc.features$mean.jerk.cost[breaks == 3], fss.features$absorption, pch = 21, cex = 1.2, ylab = absorption.expression, xlab = jerk.cost.expression)
abline(linear.model)
box()

linear.model <- lm(hrv.features$meanhr[breaks == 3] ~ (jc.features$mean.jerk.cost[breaks == 3]))
summary(linear.model)
plot(jc.features$mean.jerk.cost[breaks == 3], hrv.features$meanhr[breaks == 3], pch = 21, cex = 1.2, ylab = meanhr.expression, xlab = jerk.cost.expression)
abline(linear.model)
box()

rm(linear.model, breaks)
```

```{r linear-models-2, echo=FALSE}
breaks  <- rep(1:3, nrow(fss.features)) 
par(mfrow = c(2, 2), mar = c(3.5, 4, 1, 4) + 0.1, mgp = c(2.5, 1, 0))

linear.model <- lm(fss.features$flow ~ cls.features$mean.pcoi[breaks == 3])
summary(linear.model)
plot(cls.features$mean.pcoi[breaks == 3], fss.features$absorption, pch = 21, cex = 1.2, ylab = absorption.expression, xlab = pcoi.expression)
abline(linear.model)
box()

linear.model <- lm(hrv.features$rmssd[breaks == 3] ~ cls.features$mean.pcoi[breaks == 3])
summary(linear.model)
plot(cls.features$mean.pcoi[breaks == 3], hrv.features$rmssd[breaks == 3], pch = 21, cex = 1.2, ylab = rmssd.expression, xlab = pcoi.expression)
abline(linear.model)
box()

linear.model <- lm(jc.features$mean.jerk.cost[breaks == 3] ~ cls.features$mean.pcoi[breaks == 3])
summary(linear.model)
plot(cls.features$mean.pcoi[breaks == 3], jc.features$mean.jerk.cost[breaks == 3], pch = 21, cex = 1.2, ylab = jerk.cost.expression, xlab = pcoi.expression)
abline(linear.model)
box()

linear.model <- lm(cls.features$mean.pcoi[breaks == 3] ~ cls.features$mean.nsei[breaks == 3])
summary(linear.model)
plot(cls.features$mean.nsei[breaks == 3], cls.features$mean.pcoi[breaks == 3], pch = 21, cex = 1.2, ylab = pcoi.expression, xlab = nsei.expression)
abline(linear.model)
box()

rm(linear.model, breaks)
```

```{r process-data, echo=FALSE}

require(RHRV)
require(caTools)

sessions   <- c(12, 23)
time.range <- c(600, 900)
ticks      <- seq(time.range[1], time.range[2], 30)

for (i in sessions) {
  
  fss.feature.vector <- fss.features[i, ]
  measurement        <- fss.feature.vector$measurement
  activity.start        <- fss.feature.vector$activity.start
  fss.feature.vector <- fss.features[i-measurement+1, ]
  date.directory     <- paste(strftime(as.POSIXct(fss.feature.vector$activity.start / 1000, origin = "1970-01-01", tz="CET"), format="%Y-%m-%d--%H-%M-%S"), "/", sep ="")
  
  # Create HRV feature data frame
  directory.path  <- paste(root.data.directory.path, "processed-data/", activity.directory, user.directory, date.directory, sep="")
  file.name       <- paste("leg-cls-relative-phase-", measurement, ".csv", sep = "")
  
  data <- read.csv(paste(directory.path, file.name, sep = ""), skip = 2)
  
  par(mfcol = c(5, 1), mar = c(3.5, 4, 2, 4) + 0.1, mgp = c(2.5, 1, 0))
  
  plot(data[, 1], data[, 2], xlab = "", ylab = expression(Psi[m](tk) / (2 * pi * m)), xlim = time.range, ylim = c(0, 1), pch = 21, xaxt = "n")
  axis(1, at = ticks, labels = F)
  abline(v = ticks, lty = "dashed", col = "darkgrey")
  box()
  title(format(as.POSIXct(activity.start/1000, origin = "1970-01-01", tz = "CET"), "%Y-%m-%d %H:%M", tz = "CET"))
  
  directory.path  <- paste(root.data.directory.path, "processed-data/", activity.directory, user.directory, date.directory, sep="")
  file.name       <- paste("ecg-data-", measurement, "_hrv.txt", sep="")
  data            <- read.csv(paste(directory.path, file.name, sep = ""), header = F, na.strings = "", fill = T, skip = 117, stringsAsFactors = F, col.names = c("", "t.s", "rr.interval.s", "", "", "", "", "", "", "", ""))[,2:3]
  
  # Create hrv data
  hrv.data          <- CreateHRVData()
  hrv.data          <- SetVerbose(hrv.data, F)
  hrv.data$Beat     <- data.frame("Time" = data[,1])
  
  # Build not interpolated heart rates
  hrv.data          <- BuildNIHR(hrv.data)
  #PlotNIHR(hrv.data)
  
  # Remove artefact manually
  hrv.data          <- EditNIHR(hrv.data)
  #PlotNIHR(hrv.data)
  
  # Filter niHR automatically
  #hrv.data          <-  FilterNIHR(hrv.data)
  #PlotNIHR(hrv.data)
  
  # Create time analysis
  #hrv.data          <- CreateTimeAnalysis(hrv.data)
  
  # We create the data structure to store the nonlinear analysis
  #hrv.data <- CreateNonLinearAnalysis(hrv.data)
  
  # We calculate the Detrended Fluctuation Analysis alpha1 and alpha 2 parameters
  #hrv.data <- CalculateDFA(hrv.data, windowSizeRange = c(4, 64), npoints = 60, doPlot = F)
  #hrv.data <- EstimateDFA(hrv.data, regressionRange = c(4, 12), doPlot = F)
  #hrv.data <- EstimateDFA(hrv.data, regressionRange = c(13, 64), doPlot = F)
  
  # Linear Interpolate the data by 4 Hz (default)
  hrv.data          <- InterpolateNIHR(hrv.data)
  #PlotHR(hrv.data)
  
  # Plot spectogram with Short-time Fourier transform 30 seconds window with 1 second shift for LF
  #PlotSpectrogram(hrv.data, size=30, shift=1, freqRange=c(0.04, 0.15))
  
  # Plot spectogram with Short-time Fourier transform 30 seconds window with 1 second shift for HF-VHF
  #PlotSpectrogram(hrv.data, size=10, shift=1, freqRange=c(0.15, 0.4))
  
  # Create Frequency analysis (CWT) with least asymmetric Daubechies of width 8 for ULF, VLF, LF and HF 
  hrv.data          <- CreateFreqAnalysis(hrv.data)
  hrv.data          <- CalculatePowerBand(hrv.data, indexFreqAnalysis=1, type="wavelet", wavelet="la8", bandtolerance=0.005, ULFmin=0, ULFmax=0.0033, VLFmin=0.0033, VLFmax=0.04, LFmin=0.04, LFmax=0.15, HFmin=0.15, HFmax=0.4)
  
  # Plot bands
  #PlotPowerBand(hrv.data, indexFreqAnalysis=1, hr=TRUE)
  
  t.s <- seq(min(data[,1]),max(data[,1]), length.out = length(hrv.data$HR))
  plot(t.s, hrv.data$HR, xlab = "", ylab = expression("HR ("~BPM~")"), xlim = time.range, pch = 21, xaxt = "n")
  axis(1, at = ticks, labels = F)
  abline(v = ticks, lty = "dashed", col = "darkgrey")
  box()
  
  plot(t.s, hrv.data$FreqAnalysis[[1]]$HF, xlab = "", ylab = expression("HF ("~ms^2~")"), xlim = time.range, pch = 21, xaxt = "n")
  axis(1, at = ticks, labels = F)
  abline(v = ticks, lty = "dashed", col = "darkgrey")
  box()
  
  directory.path  <- paste(root.data.directory.path, "processed-data/", activity.directory, user.directory, date.directory, sep="")
  file.name       <- paste("leg-jerk-cost-data-", measurement, ".csv", sep="")
  data            <- read.csv(paste(directory.path, file.name, sep=""), skip = 2)
  plot(data$t.s, runmean(data$cycle.interval.s, 10, endrule = "NA"), xlab = "", ylab = expression("Cycle Interval ("~s~")"), xlim = time.range, pch = 21, xaxt = "n")
  axis(1, at = ticks, labels = F)
  abline(v = ticks, lty = "dashed", col = "darkgrey")
  box()
  plot(data$t.s, runmean(data$jerk.cost.m2s5/10^5, 10, endrule = "NA"), xlab = "", ylab = expression("JC (x"~10^5~m^2*s^{-5}~")"), xlim = time.range, pch = 21, xaxt = "n")
  axis(1, at = ticks)
  abline(v = ticks, lty = "dashed", col = "darkgrey")
  box()
}

rm(data, fss.feature.vector, activity.start, date.directory, directory.path, file.name, hrv.data, measurement, t.s, i)
```

