---
title: "Flow beim Laufen (intraindividell)"
author: "Simon Bogutzky"
date: "25. Februar 2016"
output: html_document
---
  
```{r load-data, include=FALSE}

# Remove all variables
rm(list = ls(all = T))

# Set working directory
setwd("~/psychophysiopipeline/report")

# Load functions
source("./code-snippets/functions.r")

# Set root path
root.path <- "C:/Users/sbogutzky/Desktop/data (lokal)/2013/"

# Define Colors
colors <- c("#3FADCB", "#33D100", "white")

# Set test users
user <- "buse-patrick"
activity <- "laufen"

# Collect data
data.1 <- data.frame()
data.1.pre <- data.frame()

# Load FSS features pre
fss.feature.path <- paste(root.path, "features", "/", "baseline", "/", user, "/", "fss-features.csv", sep = "")
fss.features <- read.csv(fss.feature.path)
subjects <- factor(fss.features$first.name, levels = c("Patrick"), labels = c("Male"))
data.1.pre <- rbind(data.1.pre, data.frame(subject = subjects, session.start = factor(fss.features$session.start), fss.features[, c(1:8)]))
rm(fss.feature.path)
    
# Load FSS features
fss.feature.path <- paste(root.path, "features", "/", activity, "/", user, "/", "fss-features.csv", sep = "")
fss.features <- read.csv(fss.feature.path)
rm(fss.feature.path)
    
# Load HRV features
source("code-snippets/load-hrv-features.R")
    
# Load JC features
# source("code-snippets/load-jc-features.R")
    
# Load CLS features
source("code-snippets/load-cls-features.R") 

# Set factors
subjects <- factor(fss.features$first.name, levels = c("Patrick"), labels = c("Male"))
measurements <- factor(fss.features$measurement, levels = c(1, 2, 3, 4), labels = c("15'", "30'", "45'", "60'"))
  
# Create data frame
data.1 <- rbind(data.1, data.frame(subject = subjects, session.start = factor(fss.features$session.start), measurement = measurements, fss.features[, c(1:8)], hrv.features[, c(3, 5)], cls.features[, 1:2])) #, jc.features[, 1:2]))
    
rownames(data.1) <- seq(length = nrow(data.1))

rm(user, activity, fss.features, hrv.features, cls.features, subjects, measurements) # jc.features, 
```

```{r plot}
plot(data.1$mean.nsei, data.1$absorption, xlab = "Normalized Shannon Entropy Index", ylab = "Absorption", pch = 21, bg = "tomato")  
```


```{r day-effect-on-absorption}
attach(data.1)

par(mfrow = c(1, 1))
hist(absorption)
print(shapiro.test(absorption))

mean.absorption <- tapply(absorption, date, mean, na.rm = TRUE)
sd.absorption <- tapply(absorption, date, sd, na.rm = TRUE)

par(mfrow = c(1, 1), mar = c(6, 4, 4, 2) + 0.1)
bar.plot <- barplot(mean.absorption, las = 2, ylim = c(0, 6))
arrows(bar.plot, mean.absorption - sd.absorption, bar.plot, mean.absorption + sd.absorption, angle = 90, code = 3)

aov.1 <- aov(absorption ~ date, data = data.1)
summary(aov.1)

levene(absorption, date)
summary.lm(aov.1)

pairwise.t.test(absorption, date, p.adj = "holm")

detach(data.1)
```

```{r time-effect-on-absorption}
attach(data.1)

par(mfrow = c(1, 1))
hist(absorption)
print(shapiro.test(absorption))

mean.absorption <- tapply(absorption, measurement, mean, na.rm = TRUE)
sd.absorption <- tapply(absorption, measurement, sd, na.rm = TRUE)

par(mfrow = c(1, 1), mar = c(6, 4, 4, 2) + 0.1)
bar.plot <- barplot(mean.absorption, las = 2, ylim = c(0, 6))
arrows(bar.plot, mean.absorption - sd.absorption, bar.plot, mean.absorption + sd.absorption, angle = 90, code = 3)

aov.1 <- aov(absorption ~ measurement, data = data.1)
summary(aov.1)

levene(absorption, measurement)
summary.lm(aov.1)

pairwise.t.test(absorption, measurement, p.adj = "holm")

detach(data.1)
```

```{r day-effect-on-flow}
attach(data.1)

par(mfrow = c(1, 1))
hist(flow)
print(shapiro.test(flow))

mean.flow <- tapply(flow, date, mean, na.rm = TRUE)
sd.flow <- tapply(flow, date, sd, na.rm = TRUE)

par(mfrow = c(1, 1), mar = c(6, 4, 4, 2) + 0.1)
bar.plot <- barplot(mean.flow, las = 2, ylim = c(0, 6))
arrows(bar.plot, mean.flow - sd.flow, bar.plot, mean.flow + sd.flow, angle = 90, code = 3)

aov.1 <- aov(flow ~ date, data = data.1)
summary(aov.1)

levene(flow, date)
summary.lm(aov.1)

pairwise.t.test(flow, date, p.adj = "holm")

detach(data.1)
```

```{r time-effect-on-flow}
attach(data.1)

par(mfrow = c(1, 1))
hist(flow)
print(shapiro.test(flow))

mean.flow <- tapply(flow, measurement, mean, na.rm = TRUE)
sd.flow <- tapply(flow, measurement, sd, na.rm = TRUE)

par(mfrow = c(1, 1), mar = c(6, 4, 4, 2) + 0.1)
bar.plot <- barplot(mean.flow, las = 2, ylim = c(0, 6))
arrows(bar.plot, mean.flow - sd.flow, bar.plot, mean.flow + sd.flow, angle = 90, code = 3)

aov.1 <- aov(flow ~ measurement, data = data.1)
summary(aov.1)

levene(flow, measurement)
summary.lm(aov.1)

pairwise.t.test(flow, measurement, p.adj = "holm")

detach(data.1)
```

```{r normalized-absorption-day-wise}
require(lme4) 
attach(data.1)

plot(absorption ~ date, ylim = c(2, 7))
points(data.1.pre$absorption)

mean.absorption <- tapply(absorption, date, mean, na.rm = TRUE)
plot(mean.absorption, data.1.pre$flow)
linear.model <-lm(data.1.pre$flow ~ mean.absorption)
summary(linear.model)
abline(linear.model)

absorption.matrix <- matrix(data = data.1$absorption, nrow = 6, ncol = 4, byrow = TRUE)
normalized.absorption.matrix <-absorption.matrix - data.1.pre$absorption
normalized.absorption <- c(t(normalized.absorption.matrix))

random.intercept.model <- lmer(normalized.absorption ~ (1 | date), data = data.1, REML = FALSE)
null.model <- lm(normalized.absorption ~ 1, data = data.1)

random.intercept.model.log.lik <- as.numeric(logLik(random.intercept.model))
null.model.log.lik <- as.numeric(logLik(null.model))
lr <- 2 * (random.intercept.model.log.lik - null.model.log.lik)

print(paste("LR:", lr, "chi-squared distribution on 1 d.f.:", qchisq(.95, df = 1)))

plot(mean.nsei, normalized.absorption, col = date, pch = as.numeric(measurement))
single.model <- lm(normalized.absorption ~ mean.nsei)
summary(single.model)
abline(single.model)

detach(data.1)
```

```{r normalized-flow-day-wise}
require(lme4) 
attach(data.1)

plot(flow ~ date, ylim = c(2, 7))
points(data.1.pre$flow)

mean.flow <- tapply(flow, date, mean, na.rm = TRUE)
plot(mean.flow, data.1.pre$flow)
linear.model <-lm(data.1.pre$flow ~ mean.flow)
summary(linear.model)
abline(linear.model)

flow.matrix <- matrix(data = data.1$flow, nrow = 6, ncol = 4, byrow = TRUE)
normalized.flow.matrix <-flow.matrix - data.1.pre$flow
normalized.flow <- c(t(normalized.flow.matrix))

random.intercept.model <- lmer(normalized.flow ~ (1 | date), data = data.1, REML = FALSE)
null.model <- lm(normalized.flow ~ 1, data = data.1)

random.intercept.model.log.lik <- as.numeric(logLik(random.intercept.model))
null.model.log.lik <- as.numeric(logLik(null.model))
lr <- 2 * (random.intercept.model.log.lik - null.model.log.lik)

print(paste("LR:", lr, "chi-squared distribution on 1 d.f.:", qchisq(.95, df = 1)))

plot(mean.nsei, normalized.flow, col = measurement)
single.model <- lm(normalized.flow ~ mean.nsei)
summary(single.model)
abline(single.model)

detach(data.1)
```


```{r distribution, echo=FALSE, message=FALSE, warning=FALSE}
par("mfcol" = c(2, 1), mar = c(2.5, 2.5, 2.5, 3.5) + 0.1, mgp = c(1.5, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

for(i in unique(as.numeric(data.1$subject))) {
  data.1.1 <- data.1[as.numeric(data.1$subject) == i, ]
  hist(data.1.1$absorption, main = data.1.1$subject[1], xlab = "Absorption")
  print(shapiro.test(data.1.1$absorption))
  plot(data.1.1$absorption ~ data.1.1$measurement, xlab = "Measurement", ylab = "Absorption", pch = 21, bg = colors[1])
}
rm(data.1.1, i)
```

```{r linear-models, echo=FALSE, message=FALSE, warning=FALSE}
for(i in unique(as.numeric(data.1$subject))) {
  data.1.1 <- data.1[as.numeric(data.1$subject) == i, ]
  
  par("mfcol" = c(2, 3), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")
  
  print("-----------------Mean HR-----------------")
  plot(data.1.1$absorption ~ data.1.1$meanhr, main = data.1.1$subject[1], xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$meanhr, data.1.1$absorption, x.lim = c(30, 200), sub.line = 1.3, interval = 1)
  print("-----------------------------------------")
  
  print("-----------------RMSSD-------------------")
  plot(data.1.1$absorption ~ data.1.1$rmssd, main = data.1.1$subject[1], xlab = "RMSSD", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$rmssd, data.1.1$absorption, x.lim = c(0, 20), sub.line = 1.3, interval = .5)
  print("-----------------------------------------")
  
  print("-----------------Jerk Cost---------------")
  plot(data.1.1$absorption ~ data.1.1$mean.jerk.cost, main = data.1.1$subject[1], xlab = "Jerk Cost", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$mean.jerk.cost, data.1.1$absorption, x.lim = c(1, 10), sub.line = 1.3, interval = .005)
  print("-----------------------------------------")
  
  print("-----------------Cycle Interval----------")
  plot(data.1.1$absorption ~ data.1.1$mean.cycle.interval, main = data.1.1$subject[1], xlab = "Cycle Interval", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$mean.cycle.interval, data.1.1$absorption, x.lim = c(.25, 2), sub.line = 1.3, interval = .001)
  print("-----------------------------------------")
  
  print("-----------------PCoI--------------------")
  plot(data.1.1$absorption ~ data.1.1$mean.pcoi, main = data.1.1$subject[1], xlab = "PCoI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$mean.pcoi, data.1.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
  print("-----------------------------------------")
  
  print("----------------NSEI---------------------")
  plot(data.1.1$absorption ~ data.1.1$mean.nsei, main = data.1.1$subject[1], xlab = "NSEI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.1.1$mean.nsei, data.1.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
  print("-----------------------------------------")
}

rm(data.1.1, i)
```

```{r substract-baseline-absorption, message=FALSE, warning=FALSE, include=FALSE}
data.2 <- data.1
absorption.matrix <- matrix(data = data.2$absorption, nrow = length(data.2$absorption)/4, byrow = T)
absorption.matrix <- sweep(absorption.matrix, 1, (data.1b$absorption - 1), "-")
data.2$absorption <- c(t(absorption.matrix))
data.2$absorption[data.2$absorption < 1] <- 1
rm(absorption.matrix)
```

```{r distribution-1, echo=FALSE, message=FALSE, warning=FALSE}
par("mfcol" = c(2, 1), mar = c(2.5, 2.5, 2.5, 3.5) + 0.1, mgp = c(1.5, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

for(i in unique(as.numeric(data.2$subject))) {
  data.2.1 <- data.2[as.numeric(data.2$subject) == i, ]
  hist(data.2.1$absorption, main = data.2.1$subject[1], xlab = "Absorption")
  print(shapiro.test(data.2.1$absorption))
  plot(data.2.1$absorption ~ data.2.1$measurement, xlab = "Measurement", ylab = "Absorption", pch = 21, bg = colors[1])
}
rm(data.2.1, i)
```

```{r linear-models-1, echo=FALSE, message=FALSE, warning=FALSE}
for(i in unique(as.numeric(data.1$subject))) {
  data.2.1 <- data.2[as.numeric(data.2$subject) == i, ]
  
  par("mfcol" = c(2, 3), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")
  
  print("-----------------Mean HR-----------------")
  plot(data.2.1$absorption ~ data.2.1$meanhr, main = data.2.1$subject[1], xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$meanhr, data.2.1$absorption, x.lim = c(30, 200), sub.line = 1.3, interval = 1)
  print("-----------------------------------------")
  
  print("-----------------RMSSD-------------------")
  plot(data.2.1$absorption ~ data.2.1$rmssd, main = data.2.1$subject[1], xlab = "RMSSD", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$rmssd, data.2.1$absorption, x.lim = c(0, 120), sub.line = 1.3, interval = 1)
  print("-----------------------------------------")
  
  print("-----------------Jerk Cost---------------")
  plot(data.2.1$absorption ~ data.2.1$mean.jerk.cost, main = data.2.1$subject[1], xlab = "Jerk Cost", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$mean.jerk.cost, data.2.1$absorption, x.lim = c(1, 10), sub.line = 1.3, interval = .005)
  print("-----------------------------------------")
  
  print("-----------------Cycle Interval----------")
  plot(data.2.1$absorption ~ data.2.1$mean.cycle.interval, main = data.2.1$subject[1], xlab = "Cycle Interval", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$mean.cycle.interval, data.2.1$absorption, x.lim = c(.25, 2), sub.line = 1.3, interval = .001)
  print("-----------------------------------------")
  
  print("-----------------PCoI--------------------")
  plot(data.2.1$absorption ~ data.2.1$mean.pcoi, main = data.2.1$subject[1], xlab = "PCoI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$mean.pcoi, data.2.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
  print("-----------------------------------------")
  
  print("----------------NSEI---------------------")
  plot(data.2.1$absorption ~ data.2.1$mean.nsei, main = data.2.1$subject[1], xlab = "NSEI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.2.1$mean.nsei, data.2.1$absorption, x.lim = c(0, 1), sub.line = 1.3, interval = .01)
  print("-----------------------------------------")
}

rm(data.2.1, i)
```

```{r standard-score-predictors, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
data.3 <- data.2

normalize <- function(x) {
  return(t(scale(x)[, 1]))
}

meanhr.matrix <- matrix(data = data.2$meanhr, nrow = length(data.2$meanhr)/4, byrow = T)
meanhr.matrix <- apply(meanhr.matrix, 1, normalize)

data.3$meanhr <- c(meanhr.matrix)

rmssd.matrix <- matrix(data = data.2$rmssd, nrow = length(data.2$rmssd)/4, byrow = T)
rmssd.matrix <- apply(rmssd.matrix, 1, normalize)

data.3$rmssd <- c(rmssd.matrix)

mean.jerk.cost.matrix <- matrix(data = data.2$mean.jerk.cost, nrow = length(data.2$mean.jerk.cost)/4, byrow = T)
mean.jerk.cost.matrix <- apply(mean.jerk.cost.matrix, 1, normalize)

data.3$mean.jerk.cost <- c(mean.jerk.cost.matrix)

mean.cycle.interval.matrix <- matrix(data = data.2$mean.cycle.interval, nrow = length(data.2$mean.cycle.interval)/4, byrow = T)
mean.cycle.interval.matrix <- apply(mean.cycle.interval.matrix, 1, normalize)

data.3$mean.cycle.interval <- c(mean.cycle.interval.matrix)

mean.pcoi.matrix <- matrix(data = data.2$mean.pcoi, nrow = length(data.2$mean.pcoi)/4, byrow = T)
mean.pcoi.matrix <- apply(mean.pcoi.matrix, 1, normalize)

data.3$mean.pcoi <- c(mean.pcoi.matrix)

mean.nsei.matrix <- matrix(data = data.2$mean.nsei, nrow = length(data.2$mean.nsei)/4, byrow = T)
mean.nsei.matrix <- apply(mean.nsei.matrix, 1, normalize)

data.3$mean.nsei <- c(mean.nsei.matrix)

rm(meanhr.matrix, rmssd.matrix, mean.jerk.cost.matrix, mean.cycle.interval.matrix, mean.pcoi.matrix, mean.nsei.matrix, normalize)
```

```{r linear-models-2, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
for(i in unique(as.numeric(data.2$subject))) {
  data.3.1 <- data.3[as.numeric(data.3$subject) == 1, ]
  
  par("mfcol" = c(2, 3), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")
  
  print("-----------------Mean HR-----------------")
  plot(data.3.1$absorption ~ data.3.1$meanhr, main = data.3.1$subject[1], xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$meanhr, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
  
  print("-----------------RMSSD-------------------")
  plot(data.3.1$absorption ~ data.3.1$rmssd, main = data.3.1$subject[1], xlab = "RMSSD", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$rmssd, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
  
  print("-----------------Jerk Cost---------------")
  plot(data.3.1$absorption ~ data.3.1$mean.jerk.cost, main = data.3.1$subject[1], xlab = "Jerk Cost", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$mean.jerk.cost, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
  
  print("-----------------Cycle Interval----------")
  plot(data.3.1$absorption ~ data.3.1$mean.cycle.interval, main = data.3.1$subject[1], xlab = "Cycle Interval", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$mean.cycle.interval, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
  
  print("-----------------PCoI--------------------")
  plot(data.3.1$absorption ~ data.3.1$mean.pcoi, main = data.3.1$subject[1], xlab = "PCoI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$mean.pcoi, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
  
  print("----------------NSEI---------------------")
  plot(data.3.1$absorption ~ data.3.1$mean.nsei, main = data.3.1$subject[1], xlab = "NSEI", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.3.1$mean.nsei, data.3.1$absorption, x.lim = c(-2, 2), sub.line = 1.3, interval = .1)
  print("-----------------------------------------")
}

rm(data.3.1, i)
```

```{r relations, echo=FALSE, message=FALSE, warning=FALSE}
data.4 <- data.2
data.4 <- data.4[-c(5, 18), ]

par("mfcol" = c(3, 1), mar = c(3, 3, 2.5, 1) + 0.1, mgp = c(2, .5, 0), las = 1, cex.axis = 0.8, tck = .03, cex.lab = .8, xaxs = "r", yaxs = "r")

for(i in unique(as.numeric(data.4$subject))) {
  data.4.1 <- data.4[as.numeric(data.4$subject) == i, ]
  plot(data.4.1$meanhr, data.4.1$mean.nsei, xlab = "Mean HR", ylab = "Cardio-locomotor phase synchronisation", pch = 21, bg = colors[1])
  PlotModels(data.4.1$meanhr, data.4.1$mean.nsei, x.lim = c(30, 200), sub.line = 1.25, interval = 1)
  
  plot(data.4.1$meanhr, data.4.1$absorption, xlab = "Mean HR", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.4.1$meanhr, data.4.1$absorption, x.lim = c(30, 200), sub.line = 1.25, interval = 1)
  
  plot(data.4.1$mean.nsei, data.4.1$absorption, xlab = "Cardio-locomotor phase synchronisation", ylab = "Absorption", pch = 21, bg = colors[1])
  PlotModels(data.4.1$mean.nsei, data.4.1$absorption, x.lim = c(0, 1), sub.line = 1.25, interval = .01)
}
rm(data.4.1)
```

```{r stroboscopic-technique, echo=FALSE, message=FALSE, warning=FALSE}
max.nsei <- which.max(data.2$mean.nsei)
min.nsei <- which.min(data.2$mean.nsei)
activities.1 <- rep("running", 2)
dates <- c(as.character(data.2[min.nsei,]$date), as.character(data.2[max.nsei,]$date))
measurements <- c(data.2[min.nsei,]$measurement, data.2[max.nsei,]$measurement)
subjects <- c(users[as.numeric(data.2[min.nsei,]$subject)], users[as.numeric(data.2[max.nsei,]$subject)])
time.range <- c(0, 900)
ticks <- seq(time.range[1], time.range[2], 30)
beat.plot.range <- c(150, 200)
for(i in 1:length(dates)) {
  source("code-snippets/load-and-plot-processes.R")
} 

rm(max.nsei, min.nsei, dates, measurements, subjects, activities.1, time.range, ticks, i, beat.plot.range, detail.plot.range)
```
