---
title: "Results"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(Hmisc)
library(car)
library(dplyr)

# Read data (36)
study.data <- read_csv("~/Documents/Archiv/bis 2018/studium/promotion/2016/studien/data_summary.csv")

# Remove group 4 (27)
study.data <- study.data[study.data$grp != 4, ]

# Use factor
study.data$grp <- factor(study.data$grp)

# Recode demand level
study.data$demand_level[study.data$demand_level == 6] <- 4
study.data$demand_level[study.data$demand_level == 7] <- 3
study.data$demand_level[study.data$demand_level == 8] <- 2
study.data$demand_level[study.data$demand_level == 9] <- 1
```

# Summary
```{r Summary, echo=FALSE}
print(head(data.frame(study.data[, c(11, 10, 12, 7, 8, 13)]), 30))

print(summary(study.data[, c(11, 10, 12, 7, 8, 13)]))

print(paste("absorption SD: ", sd(study.data$absorption)))
print(paste("fluency SD: ", sd(study.data$fluency)))
print(paste("demand_level SD: ", sd(study.data$demand_level)))
print(paste("pc SD: ", sd(study.data$pc)))
print(paste("nse SD: ", sd(study.data$nse)))
```

# Intercorrelations
```{r Intercorrelations, echo=FALSE}
result <- rcorr(as.matrix(study.data[, c(11, 10, 12, 7, 8)]))
print(result)

# Observed values pc
par(mfrow=c(1, 2))

plot(x = study.data$pc, y = study.data$absorption, xlab = "Phase Coherence", ylab = "", main = "Absorption", xlim = c(0, .12), ylim = c(2, 7), pch = 18, xaxs = "i", yaxs = "i")
fit.1 = lm(study.data$absorption ~ study.data$pc)
abline(fit.1)

mtext("A", side = 2, line = 3.5, padj = -27, las = 1)
print(summary(fit.1))

hist(fit.1$residuals)
shapiro.test(fit.1$residuals)

# Observed values nse
plot(x = study.data$nse, y = study.data$absorption, xlab = "Normalized Shannon Entropy", ylab = "", main = "Absorption", xlim = c(0, 0.6), ylim = c(2, 7), pch = 18, xaxs = "i", yaxs = "i")
fit.2 = lm(study.data$absorption ~ study.data$nse)
abline(fit.2)

mtext("B", side = 2, line = 3.5, padj = -27, las = 1)

print(summary(fit.2))

hist(fit.2$residuals)
shapiro.test(fit.2$residuals)
```
# ANOVA
```{r ANOVA, echo=FALSE}
print(leveneTest(study.data$absorption, study.data$grp))

print(shapiro.test(study.data[study.data$grp == 1, ]$absorption))
print(shapiro.test(study.data[study.data$grp == 2, ]$absorption))
print(shapiro.test(study.data[study.data$grp == 3, ]$absorption))

fit.aov <- aov(absorption ~ grp, data = study.data)
print(summary.aov(fit.aov))
print(TukeyHSD(fit.aov))
```

# Grp stats
```{r Grp stats, echo=FALSE}
print(group_by(study.data, grp) %>%
  summarise(
    count = n(),
    mean = mean(absorption, na.rm = TRUE),
    sd = sd(absorption, na.rm = TRUE)
  ))
```

